### ISSUE TITLE
Kumuluzee Arquillian not working with arquillian.bom 1.6.0.Final

### ISSUE THREAD

**Issue by jefrajames** [kumuluz/kumuluzee-testing#5]
Kumuluzee Arquillian is not working properly with _org.jboss.arquillian:arquillian-bom:1.6.0.Final_. The problem occurs with the code:
`PomEquippedResolveStage pom = Maven.resolver().loadPomFromFile("pom.xml");`
`File[] libs = pom.importRuntimeDependencies().resolve().withTransitivity().asFile();`
in the deployment method that returns the archive.
The error message is: `IllegalArgumentException: No dependencies were set for resolution`
It's ok when downgrading to arquillian-bom 1.4.1.Final. 

It would be nice to explicitly mention in the documentation the recommended version for arquillian-bom. I've spent a while by naively trying to use the most recent version. Maybe it's already written somewhere but I have not found it.

**Comment by MBJuric** [comment]
Thank you for your comment. We will have a look. It is true that we have developed the Arquillian adapter with version 1.4. We need to check why the latest version is not working. Please use 1.4.1 until then. Thanks.

**Comment by jefrajames** [comment]
No pb, it perfectly works with Arquillian 1.4.1
